[package]
name = "lc0441-arranging-coins"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["triangular-number"]
triangular-number = []
naive = []

[dependencies]
