[package]
name = "leetcode-rs"
version = "0.1.0"
authors = ["Roman Gafiyatullin <r.gafiyatullin@me.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# serde = { version = "^1.0", features = ["derive"] }
# serde_json = "^1.0"

# num = "^0.2"
serde = "^1.0"
serde_json = "^1.0"
# serde_derive = "^1.0"
# rustc-serialize = "^0.3"
# regex = "^1.3"
# time = "^0.1"
# text_io = "^0.1"
# rand = "^0.7"