[package]
name = "lc0659-split-array-into-consecutive-subsequences"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bench]]
name = "bench"
harness = false

[dependencies]
bencher = "^0.1"
