[package]
name = "lc2147-number-of-ways-to-divide-a-long-corridor"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
