[package]
name = "lc0835-image-overlap"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["brute-force"]
brute-force = []

[dependencies]
